[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''
build=':UpdateRemotePlugins'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'zchee/deoplete-clang'
hook_add = '''
  let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-4.0/lib/libclang.so.1'
  let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
'''
depends = ['deoplete.nvim']

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'sudar/vim-arduino-syntax'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let g:NERDTreeWinSize=26
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'stable'
build = 'bash install.sh'

[[plugins]]
repo = 'itchyny/vim-haskell-indent'
