[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
build=':UpdateRemotePlugins'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'zchee/deoplete-clang'
hook_add = '''
  let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-4.0/lib/libclang.so.1'
  let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
'''
depends = ['deoplete.nvim']

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'sudar/vim-arduino-syntax'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let g:NERDTreeWinSize=26
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'stable'
build = 'bash install.sh'

[[plugins]]
repo = 'itchyny/vim-haskell-indent'

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
hook_add = '''
  let g:haskell_enable_quantification = 1   " to enable highlighting of `forall`
  let g:haskell_enable_recursivedo = 1      " to enable highlighting of `mdo` and `rec`
  let g:haskell_enable_arrowsyntax = 1      " to enable highlighting of `proc`
  let g:haskell_enable_pattern_synonyms = 1 " to enable highlighting of `pattern`
  let g:haskell_enable_typeroles = 1        " to enable highlighting of type roles
  let g:haskell_enable_static_pointers = 1  " to enable highlighting of `static`
  let g:haskell_backpack = 1                " to enable highlighting of backpack keywords
'''
